### ISSUE TITLE
Verify panicked

### ISSUE THREAD

**Issue by gaozhengxin** [maxgillett/giza#25]
```
(cairo_venv) root@DESKTOP-1TCVFUV:/mnt/d/cairo/learn-cairo/helloworld# giza verify --proof=output.bin
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedEOF', cli/src/cmd/verify.rs:38:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Cairo program
```
func add1_square(x: felt) -> (x: felt) {
    // Call `add1` and unpack the result into `z`.
    let (z) = add1(y=x);
    return (x=z * z);
}

func add1(y: felt) -> (z: felt) {
    return (z=y + 1);
}

func main() {
    // Call `add1_square` and save the result into `res`.
    let (res) = add1_square(x=12);

    // Verify the computation.
    assert res = (12 + 1) * (12 + 1);
    return ();
}
```
Compile, run and prove cmds
```
cairo-compile hello_world.cairo --output hello_world_compiled.json
cairo-run --program=hello_world_compiled.json --layout=all --memory_file=memory.bin --trace_file=trace.bin
giza prove --trace=trace.bin --memory=memory.bin --program=hello_world_compiled.json --output=output.bin
```
Verify cmd
```
giza verify --proof=output.bin
```

**Comment by jmcph4** [comment]
So, as of 5794cc93b6ecf3fb48dc01c211f2045be1cc7f53, the proving step fails:

```
$ cairo-compile hello_world.cairo --output hello_world_compiled.json
$ cairo-run --program=hello_world_compiled.json --layout=all --memory_file=memory.bin --trace_file=trace.bin
$ giza prove --trace=trace.bin --memory=memory.bin --program=hello_world_compiled.json --output=output.bin
Built domain of 2^6 elements in 0 ms
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 0, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]`,
 right: `[15, 15, 15, 15, 15, 15, 15, 15, 15, 0, 0, 15, 15, 15, 15, 0, 15, 30, 30, 30, 15, 30, 0, 30, 0, 0, 30, 30, 30, 30, 30, 0, 15, 15, 15, 0, 15, 15, 15, 15, 15, 15, 15, 0, 15, 15, 15, 15, 15]`: transition constraint degrees didn't match
expected: [ 15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,   0,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  45,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15]
actual:   [ 15,  15,  15,  15,  15,  15,  15,  15,  15,   0,   0,  15,  15,  15,  15,   0,  15,  30,  30,  30,  15,  30,   0,  30,   0,   0,  30,  30,  30,  30,  30,   0,  15,  15,  15,   0,  15,  15,  15,  15,  15,  15,  15,   0,  15,  15,  15,  15,  15]', /home/jmcph4/.cargo/git/checkouts/winterfell-83b74b2e9a9d4ba4/0aad6a5/prover/src/constraints/evaluation_table.rs:245:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Backtrace (with `RUST_BACKTRACE=full`):

```
stack backtrace:
   0:     0x5583ea4c845a - std::backtrace_rs::backtrace::libunwind::trace::h5a7aa55788860ecf
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5583ea4c845a - std::backtrace_rs::backtrace::trace_unsynchronized::h5feae85940e4ec57
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5583ea4c845a - std::sys_common::backtrace::_print_fmt::h63373b17993242ac
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5583ea4c845a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1adbb28b9911f1db
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5583ea4e9d4e - core::fmt::write::h5e298f7e14bff76f
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/fmt/mod.rs:1208:17
   5:     0x5583ea4c59c5 - std::io::Write::write_fmt::hb5f19a0b87f55788
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/io/mod.rs:1682:15
   6:     0x5583ea4c8225 - std::sys_common::backtrace::_print::hef43593794b42a55
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5583ea4c8225 - std::sys_common::backtrace::print::h95958fd43634cef6
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5583ea4c9a0f - std::panicking::default_hook::{{closure}}::hffd4454a47e4cd07
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:267:22
   9:     0x5583ea4c974b - std::panicking::default_hook::h07dc5234e3e4775d
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:286:9
  10:     0x5583ea4ca11c - std::panicking::rust_panic_with_hook::h49245a8636ef868b
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:688:13
  11:     0x5583ea4c9eb9 - std::panicking::begin_panic_handler::{{closure}}::hcfd1ded42eb85eb2
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:579:13
  12:     0x5583ea4c890c - std::sys_common::backtrace::__rust_end_short_backtrace::h21bc7e71377619aa
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5583ea4c9bc2 - rust_begin_unwind
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:575:5
  14:     0x5583e9b0bcd3 - core::panicking::panic_fmt::h275906d1b9276a31
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/panicking.rs:64:14
  15:     0x5583e9b0c0d9 - core::panicking::assert_failed_inner::ha70dfae04a6b247a
  16:     0x5583ea0f8bca - core::panicking::assert_failed::h79a2a8e9a1de0082
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/panicking.rs:199:5
  17:     0x5583e9e753d6 - winter_prover::constraints::evaluation_table::ConstraintEvaluationTable<E>::validate_transition_degrees::hc6a4295549f34a78
                               at /home/jmcph4/.cargo/git/checkouts/winterfell-83b74b2e9a9d4ba4/0aad6a5/prover/src/constraints/evaluation_table.rs:245:9
  18:     0x5583e9e87b53 - winter_prover::constraints::evaluator::ConstraintEvaluator<A,E>::evaluate::heccd258993fa2fa2
                               at /home/jmcph4/.cargo/git/checkouts/winterfell-83b74b2e9a9d4ba4/0aad6a5/prover/src/constraints/evaluator.rs:137:9
  19:     0x5583ea1251cc - winter_prover::Prover::generate_proof::h576fc8948ed5504e
                               at /home/jmcph4/.cargo/git/checkouts/winterfell-83b74b2e9a9d4ba4/0aad6a5/prover/src/lib.rs:299:38
  20:     0x5583ea13fe88 - winter_prover::Prover::prove::h1ff7496a3509ac3b
                               at /home/jmcph4/.cargo/git/checkouts/winterfell-83b74b2e9a9d4ba4/0aad6a5/prover/src/lib.rs:168:45
  21:     0x5583e9f4c5d9 - giza_prover::prove_trace::h76b2d8130543f7c9
                               at /home/jmcph4/dev/tmp/giza/prover/src/lib.rs:23:17
  22:     0x5583e9bd7b24 - giza::cmd::prove::prove::<impl giza::utils::Cmd for giza::cmd::prove::args::ProveArgs>::run::h9490d94f06ad36dc
                               at /home/jmcph4/dev/tmp/giza/cli/src/cmd/prove/prove.rs:31:35
  23:     0x5583e9c7cfd1 - giza::main::ha370ac3b616aa02b
                               at /home/jmcph4/dev/tmp/giza/cli/src/giza.rs:26:13
  24:     0x5583e9bdd48b - core::ops::function::FnOnce::call_once::he411c777a357ce0b
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/ops/function.rs:507:5
  25:     0x5583e9be82ce - std::sys_common::backtrace::__rust_begin_short_backtrace::hcbeb785766cab45e
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/sys_common/backtrace.rs:121:18
  26:     0x5583e9ca06c1 - std::rt::lang_start::{{closure}}::h932467330471c50d
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/rt.rs:166:18
  27:     0x5583ea4c0d7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h46da8a858d500d19
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/ops/function.rs:606:13
  28:     0x5583ea4c0d7c - std::panicking::try::do_call::h41a2c5510a21211e
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:483:40
  29:     0x5583ea4c0d7c - std::panicking::try::h8f4ac87be22d0d0a
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:447:19
  30:     0x5583ea4c0d7c - std::panic::catch_unwind::hcca3aa7b89b4e0e6
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panic.rs:137:14
  31:     0x5583ea4c0d7c - std::rt::lang_start_internal::{{closure}}::hd92cac2e839cba0a
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/rt.rs:148:48
  32:     0x5583ea4c0d7c - std::panicking::try::do_call::h1657cbf60966b85d
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:483:40
  33:     0x5583ea4c0d7c - std::panicking::try::h67dd6c9618ae480f
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:447:19
  34:     0x5583ea4c0d7c - std::panic::catch_unwind::h3a772817152a1dd1
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panic.rs:137:14
  35:     0x5583ea4c0d7c - std::rt::lang_start_internal::ha05e62dea269d745
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/rt.rs:148:20
  36:     0x5583e9ca069a - std::rt::lang_start::hcc5a76de69bb0301
                               at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/rt.rs:165:17
  37:     0x5583e9c7dcae - main
  38:     0x7fe9ec99218a - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  39:     0x7fe9ec992245 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  40:     0x5583e9b0c341 - _start
  41:                0x0 - <unknown>
```

Direct site of the panic is a failed assertion:


https://github.com/maxgillett/winterfell/blob/0aad6a5b3c49a252e1c732177111bbabc99eb9bd/prover/src/constraints/evaluation_table.rs#L244-L249

**Comment by jmcph4** [comment]
Thinking this might be related to #18 due to [this comment](https://github.com/maxgillett/giza/issues/17#issuecomment-1204738785) by @maxgillett.

**Comment by maxgillett** [comment]
@jmcph4, closing this for now. Let me know if #18 was not the reason for the panic.
